environment:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  MAIL_FROM: ${MAIL_FROM}
  MAIL_TO: ${MAIL_TO}
packages:
  - name: mailer
    actions:
      - name: mailer
        runtime: 'python:default'